# Generated by Django 5.0.6 on 2024-05-20 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
            },
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API Secret')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Trading Account',
                'verbose_name_plural': 'Trading Accounts',
            },
        ),
        migrations.CreateModel(
            name='IndicatorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.FloatField(verbose_name='Numeric Value')),
                ('recognition_method',
                 models.CharField(blank=True, max_length=50, null=True, verbose_name='Recognition Method')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings',
                                                to='trading_platform.indicator', verbose_name='Indicator')),
            ],
            options={
                'verbose_name': 'Indicator Setting',
                'verbose_name_plural': 'Indicator Settings',
            },
        ),
        migrations.CreateModel(
            name='DealSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status',
                 models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive',
                                  max_length=10, verbose_name='Status')),
                ('strategy_choice', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10,
                                                     verbose_name='Strategy Choice')),
                ('indicator_settings',
                 models.ManyToManyField(to='trading_platform.indicatorsetting', verbose_name='Indicator Settings')),
                ('trading_account',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_platform.tradingaccount',
                                   verbose_name='Trading Account')),
            ],
            options={
                'verbose_name': 'Deal Settings',
                'verbose_name_plural': 'Deal Settings',
            },
        ),
    ]
