# Generated by Django 5.0.6 on 2024-05-18 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.FloatField()),
                ('recognition_method', models.CharField(blank=True, max_length=50, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_platform.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='DealSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('strategy_choice', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('indicator_settings', models.ManyToManyField(to='trading_platform.indicatorsetting')),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_platform.tradingaccount')),
            ],
        ),
    ]
