# Generated by Django 5.0.6 on 2024-05-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API Secret')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Key',
            },
        ),
        migrations.RemoveField(
            model_name='dealsettings',
            name='indicator_settings',
        ),
        migrations.RemoveField(
            model_name='dealsettings',
            name='strategy_choice',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='tradingaccount',
            name='api_secret',
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='capital_allocation',
            field=models.FloatField(blank=True, null=True, verbose_name='Capital Allocation'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='enable_long_strategy',
            field=models.BooleanField(default=False, verbose_name='Enable Long Strategy'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='enable_short_strategy',
            field=models.BooleanField(default=False, verbose_name='Enable Short Strategy'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='indicator_settings_long',
            field=models.ManyToManyField(related_name='indicator_settings_long', to='trading_platform.indicatorsetting', verbose_name='Indicator Settings Long'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='indicator_settings_short',
            field=models.ManyToManyField(related_name='indicator_settings_short', to='trading_platform.indicatorsetting', verbose_name='Indicator Settings Short'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='start_time_long',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start Time Long (minutes after market open)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='start_time_short',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start Time Short (minutes after market open)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='stop_loss_percentage_long',
            field=models.FloatField(blank=True, null=True, verbose_name='Stop Loss Percentage Long'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='stop_loss_percentage_short',
            field=models.FloatField(blank=True, null=True, verbose_name='Stop Loss Percentage Short'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_long_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage Long (1st sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_long_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage Long (2nd sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_long_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage Long (3rd sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_long_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage Long (4th sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_long_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage Long (final sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_long_time_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time in minutes (1st sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_long_time_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time in minutes (2nd sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_long_time_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time in minutes (3rd sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_long_time_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time in minutes (4th sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_long_time_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time in minutes (final sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_short_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage Short (1st sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_short_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage Short (2nd sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_short_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage Short (3rd sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_short_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage Short (4th sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_short_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage Short (final sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_short_time_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time in minutes (1st sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_short_time_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time in minutes (2nd sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_short_time_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time in minutes (3rd sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_short_time_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time in minutes (4th sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='take_profit_percentage_short_time_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time in minutes (final sequence)'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='top_stocks_long',
            field=models.IntegerField(blank=True, null=True, verbose_name='Top Stocks for Long Strategy'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='top_stocks_short',
            field=models.IntegerField(blank=True, null=True, verbose_name='Top Stocks for Short Strategy'),
        ),
        migrations.AddField(
            model_name='dealsettings',
            name='use_full_capital',
            field=models.BooleanField(default=False, verbose_name='Use Full Capital'),
        ),
    ]
