# Generated by Django 5.0.6 on 2024-05-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0002_apikey_remove_dealsettings_indicator_settings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
    ]
