# Generated by Django 5.0.6 on 2024-05-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0005_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorsetting',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='dealsettings',
            name='indicator_settings_short',
        ),
        migrations.RemoveField(
            model_name='dealsettings',
            name='indicator_settings_long',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.DeleteModel(
            name='IndicatorSetting',
        ),
    ]
