# Generated by Django 5.0.6 on 2024-05-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0007_stockmonitorconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmonitorconfiguration',
            name='email',
            field=models.EmailField(help_text='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='stockmonitorconfiguration',
            name='password',
            field=models.CharField(help_text='Password', max_length=255),
        ),
    ]
