# Generated by Django 5.0.6 on 2024-05-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0008_alter_stockmonitorconfiguration_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmonitorconfiguration',
            name='long_strategy_payload',
            field=models.JSONField(default=dict, help_text='Long Strategy Payload'),
        ),
        migrations.AddField(
            model_name='stockmonitorconfiguration',
            name='short_strategy_payload',
            field=models.JSONField(default=dict, help_text='Short Strategy Payload'),
        ),
        migrations.AddField(
            model_name='stockmonitorconfiguration',
            name='stockmonitor_cookies',
            field=models.JSONField(default=dict, help_text='Stock Monitor Cookies'),
        ),
    ]
