# Generated by Django 5.0.6 on 2024-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trading_platform', '0009_stockmonitorconfiguration_long_strategy_payload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmonitorconfiguration',
            options={'verbose_name': 'Stock Monitor Configuration',
                     'verbose_name_plural': 'Stock Monitor Configurations'},
        ),
        migrations.AlterField(
            model_name='stockmonitorconfiguration',
            name='long_strategy_payload',
            field=models.JSONField(default=dict, verbose_name='Long Strategy Payload'),
        ),
        migrations.AlterField(
            model_name='stockmonitorconfiguration',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='stockmonitorconfiguration',
            name='short_strategy_payload',
            field=models.JSONField(default=dict, verbose_name='Short Strategy Payload'),
        ),
        migrations.AlterField(
            model_name='stockmonitorconfiguration',
            name='stockmonitor_cookies',
            field=models.JSONField(default=dict, verbose_name='Stock Monitor Cookies'),
        ),
    ]
