# Generated by Django 5.0.6 on 2024-05-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0010_alter_stockmonitorconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmonitorconfiguration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
