# Generated by Django 5.0.6 on 2024-06-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0011_alter_stockmonitorconfiguration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(max_length=256, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_secret',
            field=models.CharField(max_length=256, verbose_name='API Secret'),
        ),
        migrations.AlterField(
            model_name='dealsettings',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockmonitorconfiguration',
            name='password',
            field=models.CharField(max_length=256, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='tradingaccount',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
    ]
